version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: solarwatch-postgres
    environment:
      POSTGRES_DB: solarwatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pds56ghj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solarwatch-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=Pds56ghj
      - GEO_API_KEY=${GEO_API_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-default-jwt-secret-change-me}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
